### ISSUE TITLE
Eclipse Mars support

### ISSUE THREAD

**Issue by renataogarcia** [tesla/m2eclipse-tycho#26]
Project configurators are not working on Mars Release Candidate 3 (4.5.0RC3), m2e 1.6.0.20150526.

I can confirm the plugin has been installed. I've tried 0.8 and building master(0.9):
![image](https://cloud.githubusercontent.com/assets/1123752/8264904/36ef9b7e-1730-11e5-9a61-3b501506abe8.png)

I see no errors in Eclipse log and the m2e log. The plugin doesn't seem to be picked up (_[Full Update Project log output](https://gist.github.com/renataogarcia/e034aec5dddb96f833ce)_):
```
...
20/06/2015 9:36:08 am AEST: [DEBUG] datanucleus-core is configured by :
20/06/2015 9:36:08 am AEST: [DEBUG] 	- org.eclipse.m2e.jdt.javaConfigurator
20/06/2015 9:36:08 am AEST: [DEBUG] 	- org.maven.ide.eclipse.configuration.wtp.java.unsupportedDependencyTypeConfigurator
20/06/2015 9:36:08 am AEST: [DEBUG] 	- org.eclipse.m2e.wtp.jpa.configurator.jdt
20/06/2015 9:36:08 am AEST: [DEBUG] 	- org.maven.ide.eclipse.configuration.wtp.utility.configurator
20/06/2015 9:36:08 am AEST: [DEBUG] 	- org.sonatype.m2e.mavenarchiver.jararchiverconfigurator
20/06/2015 9:36:08 am AEST: [DEBUG] 	- org.maven.ide.eclipse.configuration.wtp.webfragment.configurator
20/06/2015 9:36:08 am AEST: [DEBUG] Created marker 'Plugin execution not covered by lifecycle configuration: org.apache.felix:maven-bundle-plugin:2.4.0:manifest (execution: default, phase: process-classes)' on resource '/datanucleus-core/pom.xml'.
...
```
This same project is working on  Luna Luna Service Release 2 (4.4.2)/m2e 1.5.2.20150413-2215 and **m2e 1.6.0.20150526** as well.

```
...
20/06/2015 10:25:38 am AEST: [DEBUG] datanucleus-core is configured by :
20/06/2015 10:25:38 am AEST: [DEBUG] 	- org.eclipse.m2e.jdt.javaConfigurator
20/06/2015 10:25:38 am AEST: [DEBUG] 	- org.maven.ide.eclipse.configuration.wtp.java.unsupportedDependencyTypeConfigurator
20/06/2015 10:25:38 am AEST: [DEBUG] 	- org.eclipse.m2e.wtp.jpa.configurator.jdt
20/06/2015 10:25:38 am AEST: [DEBUG] 	- org.maven.ide.eclipse.configuration.wtp.utility.configurator
20/06/2015 10:25:38 am AEST: [DEBUG] 	- maven-bundle-plugin
20/06/2015 10:25:38 am AEST: [DEBUG] 	- pde-maven-bundle-plugin
20/06/2015 10:25:38 am AEST: [DEBUG] 	- org.maven.ide.eclipse.configuration.wtp.webfragment.configurator
...
```
Not sure if this is relevant but:
Luna - org.sonatype.m2e.mavenarchiver.feature (0.16.0.201401211452-signed-20140310144306)
Mars - org.sonatype.m2e.mavenarchiver.feature (0.17.0.201502101659-signed-20150525172209)

**Comment by ifedorenko** [comment]
Generally, m2e-tycho works with latest eclipse and m2e, so there must be something special about your project or environment. I suspect there is an incompatibility with one of the other eclipse plugins you have install. I recommend setting up simple standalone project first, than gradually add features to see at which point it stops working. Once you know what triggers the problem, we can decide what to do about it.

**Comment by renataogarcia** [comment]
Thanks for the quick reply! I tried reinstalling everything from scratch into a new workspace and it worked. I've pointed the new installation to the old workspace and it also worked. Not sure what went different this time though. Sorry about the noise!
