### ISSUE TITLE
Create 0.8.x branch

### ISSUE THREAD

**Issue by apupier** [tesla/m2eclipse-tycho#33]

**Comment by apupier** [comment]
as there is no tag, I supposed that the right commit to start branch is https://github.com/tesla/m2eclipse-tycho/commit/cd277ca497196f70c807a1828b37d9f80b05ab71 as the plugin qualifier is org.sonatype.tycho.m2e 0.8.0.201409231215

**Comment by fbricon** [comment]
0.8.x pushed, based off cd277ca
